apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    name: hello-app
spec:
  containers:
  - name: hello-app
    image: docker.io/frodetbj/fireside-demo-app:hello
    ports:
    - containerPort: 8080
