apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-app
  labels:
    name: hello-app
spec:
  replicas: 3
  selector:
    name: hello-app
  template:
    metadata:
      labels:
        name: hello-app
    spec:
      containers:
      - name: hello-app
        image: docker.io/frodetbj/fireside-demo-app:hello
        ports:
        - containerPort: 8080
